- Sandwich/Sandwich.iml
- Sandwich/src/Main.java
[ SCRUM-3 / test ]
Jira - Github 연동 테스트
> Jira - Github 연동 테스트

- Sandwich/src/main/java/com/sandwich/SandWich/auth/controller/AuthController.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/dto/SignupRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/dto/TokenResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/JwtUtil.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/service/AuthService.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/validation/PasswordConstraintValidator.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/validation/ValidPassword.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/exception/RestExceptionHandler.java
- Sandwich/src/main/java/com/sandwich/SandWich/oauth/handler/CustomAuthorizationRequestResolver.java
- Sandwich/src/main/java/com/sandwich/SandWich/oauth/handler/OAuth2FailureHandler.java
- Sandwich/src/main/java/com/sandwich/SandWich/oauth/handler/OAuth2SuccessHandler.java
- Sandwich/src/main/java/com/sandwich/SandWich/oauth/model/CustomOAuth2User.java
- Sandwich/src/main/java/com/sandwich/SandWich/oauth/service/CustomOAuth2UserService.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
Jira 백로그 >>
https://hyeonjujo999.atlassian.net/browse/SCRUM-20?atlOrigin=eyJpIjoiMjI0M2IwOTllZWI4NGE4YWJiMjg3NDBhOTNhMWM3MzMiLCJwIjoiaiJ9
> SCRUM-20 로그아웃 기능 구현 

- Sandwich/src/main/java/com/sandwich/SandWich/auth/controller/AuthController.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/dto/SignupRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/dto/TokenResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/JwtFilter.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/JwtUtil.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/service/AuthService.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/validation/PasswordConstraintValidator.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/validation/ValidPassword.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/exception/RestExceptionHandler.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/GlobalExceptionHandler.java
- Sandwich/src/main/java/com/sandwich/SandWich/oauth/handler/CustomAuthorizationRequestResolver.java
- Sandwich/src/main/java/com/sandwich/SandWich/oauth/handler/OAuth2FailureHandler.java
- Sandwich/src/main/java/com/sandwich/SandWich/oauth/handler/OAuth2SuccessHandler.java
- Sandwich/src/main/java/com/sandwich/SandWich/oauth/model/CustomOAuth2User.java
- Sandwich/src/main/java/com/sandwich/SandWich/oauth/service/CustomOAuth2UserService.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/User.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/repository/UserRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
Jira 백로그 >>
https://hyeonjujo999.atlassian.net/browse/SCRUM-21?atlOrigin=eyJpIjoiMzY5Zjc2NTFlYzVjNGQxMjg0ZDAxYWZkMjhmZmE2YTAiLCJwIjoiaiJ9
> SCRUM-21 회원 탈퇴 기능 구현

- Sandwich/docker-compose.yml
- Sandwich/src/main/resources/application.properties
Jira 백로그 >>
https://hyeonjujo999.atlassian.net/browse/SCRUM-25?atlOrigin=eyJpIjoiNTczNzU3MTI2NzQyNGM4M2IzYmU1ZTlmNzE0MGYyZDciLCJwIjoiaiJ9
> SCRUM-25 기존 수동 컨테이너 방식 → docker-compose 자동 관리 방식으로 전환

- .idea/.gitignore
- .idea/.name
- .idea/compiler.xml
- .idea/dataSources.xml
- .idea/gradle.xml
- .idea/misc.xml
- .idea/vcs.xml
- Sandwich/Dockerfile
- Sandwich/docker-compose.dev.yml
- Sandwich/docker-compose.yml
- Sandwich/src/main/resources/application.properties
- Sandwich/src/main/resources/application.yml
[ feat / SCRUM-31 ]: Docker 전체 실행 / 개발 모드 구분
Docker 개발 진행 중
실행 커맨드
**[IDE에서 실행 - 개발 중 빠른 실행]**
`docker-compose up -d`
**[Docker 컨테이너 - 통합 테스트/배포]**
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build`
https://hyeonjujo999.atlassian.net/browse/SCRUM-31
> [ feat / SCRUM-31 ]: Docker 전체 실행 / 개발 모드 구분

- Sandwich/build.gradle.kts
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/controller/ProjectContentController.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/controller/ProjectController.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/ContentType.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/Project.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/ProjectContent.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectContentRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectContentUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ReorderRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/repository/ProjectContentRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/repository/ProjectRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/service/ProjectContentService.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/service/ProjectService.java
- Sandwich/src/main/java/com/sandwich/SandWich/upload/config/S3Config.java
- Sandwich/src/main/java/com/sandwich/SandWich/upload/controller/ImageUploadController.java
- Sandwich/src/main/java/com/sandwich/SandWich/upload/util/S3Uploader.java
- Sandwich/src/main/resources/application.properties
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-26?atlOrigin=eyJpIjoiZWQyYzVlNWM2MWIwNGMzNThhY2ZhZThkZjAxODA5YzUiLCJwIjoiaiJ9
> SCRUM-26 프로젝트 등록

- Sandwich/build.gradle.kts
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/controller/ProjectContentController.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/controller/ProjectController.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/ContentType.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/Project.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/ProjectContent.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectContentRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectContentUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectDetailResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ReorderRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/repository/ProjectContentRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/repository/ProjectRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/service/ProjectContentService.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/service/ProjectService.java
- Sandwich/src/main/java/com/sandwich/SandWich/upload/config/S3Config.java
- Sandwich/src/main/java/com/sandwich/SandWich/upload/controller/ImageUploadController.java
- Sandwich/src/main/java/com/sandwich/SandWich/upload/util/S3Uploader.java
- Sandwich/src/main/resources/application.properties
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-27?atlOrigin=eyJpIjoiODZlOGI1MGUyMTdhNGEzOGI1YTFmODUxMzNhMWQ3MTAiLCJwIjoiaiJ9
> SCRUM-27 단순 프로젝트 조회

- Sandwich/build.gradle.kts
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/util/QRCodeGenerator.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/controller/ProjectContentController.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/controller/ProjectController.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/ContentType.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/Project.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/ProjectContent.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectContentRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectContentUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectDetailResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ReorderRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/repository/ProjectContentRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/repository/ProjectRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/service/ProjectContentService.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/service/ProjectService.java
- Sandwich/src/main/java/com/sandwich/SandWich/upload/config/S3Config.java
- Sandwich/src/main/java/com/sandwich/SandWich/upload/controller/ImageUploadController.java
- Sandwich/src/main/java/com/sandwich/SandWich/upload/util/S3Uploader.java
- Sandwich/src/main/resources/application.properties
Jira 백로그 >>https://hyeonjujo999.atlassian.net/browse/SCRUM-28?atlOrigin=eyJpIjoiNzZhNmZkMjA3ZjUyNGRjMGFkNjM3NDg3NGViOTU5MjkiLCJwIjoiaiJ9
> SCRUM-28 QR 코드 생성

- Sandwich/build.gradle.kts
- Sandwich/src/main/java/com/sandwich/SandWich/community/domain/Comment.java
- Sandwich/src/main/java/com/sandwich/SandWich/community/domain/Post.java
- Sandwich/src/main/java/com/sandwich/SandWich/community/repository/CommentRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/community/repository/PostRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
- Sandwich/src/test/java/com/sandwich/SandWich/user/UserDeleteIntegrationTest.java
- Sandwich/src/test/resources/application.properties
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-38?atlOrigin=eyJpIjoiZWU5ODJjYjExMzM3NDE3NzhjZDA5MjczM2JjZmY1NTkiLCJwIjoiaiJ9
> REAL SCRUM-38 merge

- Sandwich/src/main/java/com/sandwich/SandWich/auth/dto/SignupRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/UserDetailsImpl.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/service/AuthService.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/domain/ChallengeOption.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/domain/Comment.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/dto/CommentRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/dto/CommentResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/repository/CommentRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/service/CommentService.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/GlobalExceptionHandler.java
- Sandwich/src/main/java/com/sandwich/SandWich/post/domain/Post.java
- Sandwich/src/main/java/com/sandwich/SandWich/post/repository/PostRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/Project.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/domain/Follow.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/domain/Like.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/Profile.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/User.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/UserProfileRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/repository/ProfileRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/repository/UserRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
- Sandwich/src/test/java/com/sandwich/SandWich/user/UserDeleteIntegrationTest.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-39?atlOrigin=eyJpIjoiYWU3YTczNGNhYzQ3NDE4MWI1YmNiNTdjY2U2NmZkM2MiLCJwIjoiaiJ9
> [ feat / SCRUM-39 ] nickname 기능 추가

- Sandwich/src/main/java/com/sandwich/SandWich/auth/dto/SignupRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/UserDetailsImpl.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/service/AuthService.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/domain/ChallengeOption.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/controller/CommentController.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/domain/Comment.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/dto/CommentRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/dto/CommentResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/repository/CommentRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/service/CommentService.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/GlobalExceptionHandler.java
- Sandwich/src/main/java/com/sandwich/SandWich/post/domain/Post.java
- Sandwich/src/main/java/com/sandwich/SandWich/post/repository/PostRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/Project.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/domain/Follow.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/domain/Like.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/Profile.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/User.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/UserProfileRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/repository/ProfileRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/repository/UserRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
- Sandwich/src/test/java/com/sandwich/SandWich/user/UserDeleteIntegrationTest.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-40?atlOrigin=eyJpIjoiNTlkM2I0MGFjYzZmNGEzMGE3MmY2NzQwNThmNGI5NjYiLCJwIjoiaiJ9
> [ feat / SCRUM-40 ] 프로젝트 댓글 CRUD

- Sandwich/src/main/java/com/sandwich/SandWich/auth/controller/AuthController.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/dto/SignupRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/UserDetailsImpl.java
- Sandwich/src/main/java/com/sandwich/SandWich/auth/service/AuthService.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/domain/ChallengeOption.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/controller/CommentController.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/domain/Comment.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/dto/CommentRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/dto/CommentResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/repository/CommentRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/service/CommentService.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/GlobalExceptionHandler.java
- Sandwich/src/main/java/com/sandwich/SandWich/post/domain/Post.java
- Sandwich/src/main/java/com/sandwich/SandWich/post/repository/PostRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/Project.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/domain/Follow.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/domain/Like.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/Profile.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/User.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/UserProfileRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/repository/ProfileRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/repository/UserRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
- Sandwich/src/test/java/com/sandwich/SandWich/user/UserDeleteIntegrationTest.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-41?atlOrigin=eyJpIjoiZTdmYjY4NmQ3Mjk5NGQzYWI2ZDliMTIwZGM3OGE3ZjEiLCJwIjoiaiJ9
> [ feat / SCRUM-41 ] 닉네임 중복 확인 API

- Sandwich/.github/workflows/main.yml
- Sandwich/buildspec.yml
[ feat / SCRUM-49 ] GitHub Actions로 Docker 이미지 빌드 + ECR 푸시
> [ feat / SCRUM-49 ] GitHub Actions로 Docker 이미지 빌드 + ECR 푸시

- Sandwich/Dockerfile
- Sandwich/docker-compose.yml
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/Interest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/InterestType.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/User.java
- Sandwich/src/main/resources/application.properties
- Sandwich/src/test/java/com/sandwich/SandWich/auth/AuthIntegrationTest.java
- Sandwich/src/test/java/com/sandwich/SandWich/user/UserDeleteIntegrationTest.java
- Sandwich/src/test/resources/application.properties
Jira 백로그 >>https://hyeonjujo999.atlassian.net/browse/SCRUM-44?atlOrigin=eyJpIjoiMTU2MGY1YmVhY2EyNGUxOTljYzQ3OTkwZTUyMzk4Y2IiLCJwIjoiaiJ9
> [ fix / #44 ] window local port 충돌 해결

- Sandwich/src/main/java/com/sandwich/SandWich/SandWichApplication.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/util/RedisUtil.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/controller/ProjectController.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/Project.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/domain/ProjectView.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/repository/ProjectViewRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/scheduler/ProjectViewSyncScheduler.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/service/ProjectViewService.java
- front/package-lock.json
- front/package.json
Jira 백로그 >>https://hyeonjujo999.atlassian.net/browse/SCRUM-63?atlOrigin=eyJpIjoiMGQ1MTNhYjdjMmE4NGI2M2FkMWM5Y2JiOGExMTc2NTkiLCJwIjoiaiJ9
> [ feat / SCRUM-63 ] 조회수 로직

- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/util/PasswordEncoderTest.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/UserNotFoundException.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/dto/FollowNotificationPayload.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/service/FollowNotificationService.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/controller/ProjectController.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/controller/ProjectViewController.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectViewDto.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/repository/ProjectViewRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/service/ProjectViewQueryService.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/service/ProjectViewService.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/controller/FollowController.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/domain/Follow.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/repository/FollowRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/service/FollowService.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/Role.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/User.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
Jira 백로그 >>https://hyeonjujo999.atlassian.net/browse/SCRUM-74?atlOrigin=eyJpIjoiNGJmNDkxOGM0YjA4NGJmOWE0ZjE0MTI1ZDJiYzQxNDYiLCJwIjoiaiJ9
> [ feat / SCRUM-74 ] 언팔로우 api

- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/util/PasswordEncoderTest.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/UserNotFoundException.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/dto/FollowNotificationPayload.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/service/FollowNotificationService.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/controller/ProjectController.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/controller/ProjectViewController.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/dto/ProjectViewDto.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/repository/ProjectViewRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/service/ProjectViewQueryService.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/service/ProjectViewService.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/controller/FollowController.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/domain/Follow.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/repository/FollowRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/service/FollowService.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/Role.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/domain/User.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/FollowingUserResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-77?atlOrigin=eyJpIjoiYTlhMTk0YmRiYWViNDU4NDkzYWUzMWM2OWZhNzNiNGEiLCJwIjoiaiJ9
> [ feat / SSCRUM-77 ] 팔로잉 목록 조회 api

- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/controller/FollowController.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/repository/FollowRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/social/service/FollowService.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/SimpleUserResponse.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-78?atlOrigin=eyJpIjoiZmI5MWNlNzJjNDk2NDdmMmE4MDE5NWFjNGY2OGFhOGMiLCJwIjoiaiJ9
> [ feat SCRUM-78 ] 팔로워 목록 조회 api

- Sandwich/src/main/java/com/sandwich/SandWich/social/controller/FollowController.java
[ feat / SCRUM-87 ] FollowController.java getFollowers 중복 제거
> [ feat / SCRUM-87 ] FollowController.java getFollowers 중복 제거

- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/PositionResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/PositionUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
Jirs 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-93?atlOrigin=eyJpIjoiMDUyZGFjYjNlODdjNDBkZDgzNDlkMTMzM2Q5NmJjZGUiLCJwIjoiaiJ9
> [ feat / SCRUM-93 ] 작업 분야 api

- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/InterestResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/InterestUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/PositionResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/PositionUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-94?atlOrigin=eyJpIjoiOGQzZjM5OGU0NmVkNGNjMDg5MjRhOGQ2NmJjNTE4ODUiLCJwIjoiaiJ9
> [ feat / SCRUM-94 ] 관심 분야 api

- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/InterestResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/InterestUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/PositionResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/PositionUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-95?atlOrigin=eyJpIjoiMDFmNzlmMmVjNzMyNGNkMmIzYjIzNjVlYjk3YWVhNDgiLCJwIjoiaiJ9
> [ feat / SCRUM-95 ] 기술 스택 api

- Sandwich/src/main/java/com/sandwich/SandWich/award/controller/AwardController.java
- Sandwich/src/main/java/com/sandwich/SandWich/award/domain/Award.java
- Sandwich/src/main/java/com/sandwich/SandWich/award/dto/AwardRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/award/dto/AwardResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/award/repository/AwardRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/award/service/AwardService.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/controller/CareerController.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/domain/Career.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/dto/CareerRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/dto/CareerResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/repository/CareerRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/service/CareerService.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/controller/CareerProjectController.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/domain/CareerProject.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/dto/CareerProjectRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/dto/CareerProjectResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/repository/CareerProjectRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/service/CareerProjectService.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/controller/EducationController.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/domain/Education.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/dto/EducationRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/dto/EducationResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/repository/EducationRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/service/EducationService.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/InterestResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/InterestUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/PositionResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/PositionUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-99?atlOrigin=eyJpIjoiMDlhMzQ3ZWFjMGEwNDI5OWFjMjk1NjQ0YWEzNGMwMTgiLCJwIjoiaiJ9
> [ feat / SCRUM-99 ] career project 설정

- Sandwich/src/main/java/com/sandwich/SandWich/award/controller/AwardController.java
- Sandwich/src/main/java/com/sandwich/SandWich/award/domain/Award.java
- Sandwich/src/main/java/com/sandwich/SandWich/award/dto/AwardRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/award/dto/AwardResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/award/repository/AwardRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/award/service/AwardService.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/controller/CareerController.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/domain/Career.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/dto/CareerRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/dto/CareerResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/repository/CareerRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/career/service/CareerService.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/controller/CareerProjectController.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/domain/CareerProject.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/dto/CareerProjectRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/dto/CareerProjectResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/repository/CareerProjectRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/careerProject/service/CareerProjectService.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/controller/EducationController.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/domain/Education.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/dto/EducationRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/dto/EducationResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/repository/EducationRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/education/service/EducationService.java
- Sandwich/src/main/java/com/sandwich/SandWich/representative/controller/RepresentativeCareerController.java
- Sandwich/src/main/java/com/sandwich/SandWich/representative/dto/RepresentativeCareerResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/InterestResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/InterestUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-100?atlOrigin=eyJpIjoiZDc3MGM5YTU3MzcxNGM0OThhYTNjMzZhNWI4YjA0OGIiLCJwIjoiaiJ9
> [ feat / SCRUM-100 ] 통합 대표 커리어 조회

- Sandwich/src/main/java/com/sandwich/SandWich/GitHubRequest/service/GitHubBranchService.java
- Sandwich/src/main/java/com/sandwich/SandWich/GitHubRequest/service/WorkflowFileService.java
[ feat / SCRUM-84 ] GitHub Actions 워크플로우 파일 생성
[ fix / SCRUM-101 ] GitHub 브랜치 자동 생성 중복 오류 대응
> [ feat / SCRUM-84 ] GitHub Actions 워크플로우 파일 생성

- Sandwich/src/main/java/com/sandwich/SandWich/collection/controller/CollectionController.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/domain/CollectionFolder.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/domain/CollectionItem.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/dto/AddToCollectionRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/dto/CollectionFolderDetailResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/dto/CollectionFolderRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/dto/CollectionFolderResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/dto/ProjectSummary.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/dto/RemoveFromCollectionRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/repository/CollectionFolderRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/repository/CollectionItemRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/service/CollectionService.java
- Sandwich/src/main/java/com/sandwich/SandWich/collection/service/CollectionServiceImpl.java
- Sandwich/src/main/java/com/sandwich/SandWich/comment/repository/CommentRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/CollectionFolderNotFoundException.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/ForbiddenAccessException.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/ProjectNotFoundException.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-103?atlOrigin=eyJpIjoiMDFlZDQ3Yzg2ZjJmNDI0Mzg2YzgzNzc4Y2MwNzc2ZDUiLCJwIjoiaiJ9
> [ feat / SCRUM-103 ] collection 기능

- Sandwich/src/main/java/com/sandwich/SandWich/GitHubRequest/service/GitHubBranchService.java
- Sandwich/src/main/java/com/sandwich/SandWich/GitHubRequest/service/WorkflowFileService.java
[ fix / SCRUM-102 ] CloudFront 캐시 무효화 오류 해결
> [ fix / SCRUM-102 ] CloudFront 캐시 무효화 오류 해결

- Sandwich/src/main/java/com/sandwich/SandWich/GitHubRequest/service/WorkflowFileService.java
[ feat / SCRUM-85 ] .sandwich.json 기반으로 빌드 명령 파싱
> [ feat / SCRUM-85 ] .sandwich.json 기반으로 빌드 명령 파싱

- Sandwich/src/main/java/com/sandwich/SandWich/message/controller/MessageController.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/controller/MessagePreferenceController.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/controller/PublicUserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/domain/Message.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/domain/MessageRoom.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/domain/UserMessagePreference.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/dto/MessagePreferenceResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/dto/MessageResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/dto/MessageType.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/dto/SendMessageRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/dto/UpdateMessagePreferenceRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/repository/MessageRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/repository/MessageRoomRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/repository/UserMessagePreferenceRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/service/MessagePreferenceService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/service/MessageService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-110?atlOrigin=eyJpIjoiZTc5NmU1YWQwMjc3NGNmMjkyMGI0NDk1Nzc4MjRiNDIiLCJwIjoiaiJ9
> [ feat / SCRUM-110 ] 메세지 전송

- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/MessageNotAllowedException.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/service/MessageService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-115?atlOrigin=eyJpIjoiNzk1YmQ4NmMyMDJhNGY5N2E4MjVlZGI2ZDVhYmRjMTUiLCJwIjoiaiJ9
> [ feat / SCRUM-115 ] 차단 로직 전용 예외 클래스

- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/MessageNotAllowedException.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/MessageRoomForbiddenException.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/MessageRoomNotFoundException.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/controller/MessageController.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/repository/MessageRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/service/MessageService.java
Jira 백로그 >> eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MkBzYW5kd2ljaC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzU0OTEwNzk0fQ.5y5pi_T6Uc_kLVhvX2iWDAGOh42EmCrMW-vMNFjF1kY
> [ feat / SCRUM-117 ] 메세지 읽음

- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/MessageNotAllowedException.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/MessageNotFoundException.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/MessageRoomForbiddenException.java
- Sandwich/src/main/java/com/sandwich/SandWich/global/exception/exceptiontype/MessageRoomNotFoundException.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/controller/MessageController.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/repository/MessageRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/service/MessageService.java
백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-118?atlOrigin=eyJpIjoiODU2OWI1OTJiMzRiNGQ2YWI1NTgyZGI2NzBmMjYzNmIiLCJwIjoiaiJ9
> [ feat / SCRUM-118 ] 메세지 단일 조회

- Sandwich/src/main/java/com/sandwich/SandWich/message/domain/Message.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-125?atlOrigin=eyJpIjoiMzJkYTVhZjk2NmU1NDFkNDljMWIyOGYxNjliNDZkYTUiLCJwIjoiaiJ9
> [ fix / SCRUM-125 ] 중복 필드 제거

- Sandwich/src/main/java/com/sandwich/SandWich/message/domain/Message.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/domain/MessageRoom.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/domain/UserMessagePreference.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/repository/MessageRoomRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/room/controller/RoomController.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/room/dto/RoomListItemResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/room/repository/RoomListRow.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/room/service/RoomQueryService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/service/MessageService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-128?atlOrigin=eyJpIjoiMjFkYzJlODllYmNhNDI1MjllZDc3ZmY5YmQ0MGFhNDEiLCJwIjoiaiJ9
> [ feat / SCRUM-128 ] 자신이 참여한 모든 채팅방 조회

- Sandwich/src/main/java/com/sandwich/SandWich/config/PlaywrightConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/domain/AttachmentMetadata.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/service/AttachmentService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/storage/LocalStorageService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/storage/S3StorageService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/storage/StorageService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/util/ChatScreenshotRendererText.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/util/DefaultThumbnailResolver.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/util/ThumbnailResolver.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/service/MessageScreenshotService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/service/MessageService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/util/ChatScreenshotHtmlRenderer.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/util/ChatScreenshotRenderer.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-147?atlOrigin=eyJpIjoiNGQwMzRlZjg0ZTYyNDk5YTkwYWRkNTJiZGY2YzBjNTciLCJwIjoiaiJ9
> [ feat / SCRUM-147 ] 첨부파일 스크린샷 렌더링

- Sandwich/build.gradle.kts
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/config/PlaywrightConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/domain/AttachmentMetadata.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/service/AttachmentService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/storage/LocalStorageService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/storage/S3StorageService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/storage/StorageService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/util/ChatScreenshotRendererText.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/util/DefaultThumbnailResolver.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/attach/util/ThumbnailResolver.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/service/MessageScreenshotService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/service/MessageService.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/util/ChatScreenshotHtmlRenderer.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/util/ChatScreenshotRenderer.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/JwtHandshakeInterceptor.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/MessageWsController.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/PrincipalHandshakeHandler.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/StompAuthChannelInterceptor.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/WebSocketConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/dto/WsMessageBroadcast.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/dto/WsSendMessageRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/ws-test.html
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-152?atlOrigin=eyJpIjoiNjQ5MjhkYTc0MjNmNGM5ZWI4MzEyYWQ5ZTcxNGYyOTgiLCJwIjoiaiJ9
> [ feat / SCRUM-152 ] web socket end point

- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/UserProfileResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/repository/UserRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-158?atlOrigin=eyJpIjoiZTlhZDFjOGY5NzIxNGFmMGFlZTNlNzU3ODlkZDVlNTEiLCJwIjoiaiJ9
> [ feat / SCRUM-158 ] [프런트 요청] nickname필드 추가

- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/StompAuthChannelInterceptor.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/testHtml/ws-test.html
- Sandwich/src/main/java/com/sandwich/SandWich/notification/NotificationPublisher.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/dev/DevNotifyController.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/dto/NotifyEvent.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/dto/NotifyPayload.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/events/CommentCreatedEvent.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/handlers/CommentNotifyListener.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/service/FollowNotificationService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-161?atlOrigin=eyJpIjoiNTliYTJlMmIyOTk2NDI1M2E5N2EyNGVmNWE4MTI3YTIiLCJwIjoiaiJ9
> [ feat / SCRUM-161 ] 개인 토픽 ws 오픈

- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/StompAuthChannelInterceptor.java
- Sandwich/src/main/java/com/sandwich/SandWich/message/ws/testHtml/ws-test.html
- Sandwich/src/main/java/com/sandwich/SandWich/notification/NotificationPublisher.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/controller/NotificationPreferenceController.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/dev/DevNotifyController.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/domain/NotificationPreference.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/dto/NotificationPrefsResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/dto/NotificationPrefsUpdateRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/dto/NotifyEvent.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/dto/NotifyPayload.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/events/CommentCreatedEvent.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/fanout/EmailSender.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/fanout/NoopEmailSender.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/fanout/NoopPushSender.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/fanout/NotificationFanoutService.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/fanout/NotifyChannel.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/fanout/NotifyKind.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/fanout/PreferenceChecker.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/fanout/PushSender.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/handlers/CommentNotifyListener.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/repository/NotificationPreferenceRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/service/FollowNotificationService.java
- Sandwich/src/main/java/com/sandwich/SandWich/notification/service/NotificationPreferenceService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-162?atlOrigin=eyJpIjoiNGUxNzVhMTg0ZmMxNDgyZWFhYzRhNWRkMWI5N2ZhNGIiLCJwIjoiaiJ9
> [ feat / SCRUM-162  ] 알림 preferences

- Sandwich/src/main/java/com/sandwich/SandWich/challenge/domain/Submission.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/dto/SubmissionDtos.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/repository/SubmissionAssetRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/service/SubmissionService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-179?atlOrigin=eyJpIjoiN2VlMTkxZGNlYzVkNDZjMjkzNTUzY2Q4YThmNWYwNjEiLCJwIjoiaiJ9
> [ feat / SCRUM-179 ] portfolio submission 보강

- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/controller/LeaderboardController.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/domain/Submission.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/dto/LeaderboardDtos.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/dto/SubmissionDtos.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/notify/PortfolioNotifyListener.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/repository/PortfolioVoteRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/repository/SubmissionAssetRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/service/PortfolioLeaderboardCache.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/service/PortfolioVoteService.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/service/SubmissionService.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/config/RedisConfig.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-181?atlOrigin=eyJpIjoiNjMzOGI2NTMwMTQzNDhkMjk3Njg2MzQyMTdmOGRkNDIiLCJwIjoiaiJ9
> [ feat / SCRUM-181 ] portfolio notify

- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/controller/LeaderboardController.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/controller/SubmissionController.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/domain/CodeSubmission.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/domain/Submission.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/domain/SubmissionStatus.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/dto/LeaderboardDtos.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/dto/SubmissionDtos.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/notify/PortfolioNotifyListener.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/repository/CodeSubmissionRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/repository/PortfolioVoteRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/repository/SubmissionAssetRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/service/PortfolioLeaderboardCache.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/service/PortfolioVoteService.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/service/SubmissionService.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/config/RedisConfig.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-182?atlOrigin=eyJpIjoiNjA0ZjRlOTAwMjU0NDQzYThkMDQyY2FjNGRjZjZiM2YiLCJwIjoiaiJ9
> [ feat / SCRUM-182 ] code submission

- Sandwich/build.gradle.kts
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/event/CodeSubmissionCreatedEvent.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/repository/CodeSubmissionRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/service/SubmissionService.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/GradeClient.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/GradeProducerListener.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/GradeRequestService.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/GraderConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/GraderProperties.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/HmacSigner.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/dto/GradeRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/dto/GradeRequestPreview.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/dto/GradeResponseEnvelope.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/web/GraderDevController.java
- Sandwich/src/main/resources/application.properties
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-183?atlOrigin=eyJpIjoiYmQ0ZTk2Y2I5ZTU3NDQzODkwY2Y5OTVlOTBmOTMwYWUiLCJwIjoiaiJ9
> [ feat / SCRUM-183 ] code grader request

- Sandwich/build.gradle.kts
- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/event/CodeSubmissionCreatedEvent.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/repository/CodeSubmissionRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/challenge/service/SubmissionService.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/GradeClient.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/GradeProducerListener.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/GradeRequestService.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/GraderConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/GraderProperties.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/HmacSigner.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/HmacVerifier.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/domain/TestResult.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/dto/GradeCallbackRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/dto/GradeRequest.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/dto/GradeRequestPreview.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/dto/GradeResponseEnvelope.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/repository/TestResultRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/service/GradeCallbackService.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/web/GradeCallbackController.java
- Sandwich/src/main/java/com/sandwich/SandWich/grader/web/GraderDevController.java
- Sandwich/src/main/resources/application.properties
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-184?atlOrigin=eyJpIjoiNGFlYTRkNzRjYTU0NDNhMThhZjZhMjVkMGYyZTYzMjUiLCJwIjoiaiJ9
> [ feat / SCRUM-184 ] code grader callback

- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/captcha/GoogleRecaptchaVerifier.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/captcha/NoopRecaptchaVerifier.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/captcha/RecaptchaFilter.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/captcha/RecaptchaProperties.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/captcha/RecaptchaV2Service.java
- Sandwich/src/main/java/com/sandwich/SandWich/common/captcha/RecaptchaVerifier.java
- Sandwich/src/main/java/com/sandwich/SandWich/email/controller/EmailVerificationController.java
- Sandwich/src/main/resources/application.properties
- Sandwich/src/main/resources/static/recaptcha-v2.html
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-196?atlOrigin=eyJpIjoiZjFkNzc5MmViZjZhNDQ4NmJmZWIzNDg4MWZiMmVkNzUiLCJwIjoiaiJ9
> [ feat / SCRUM-196 ] reCAPTCHA filter V2

- Sandwich/src/main/java/com/sandwich/SandWich/auth/security/SecurityConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/controller/UserController.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/PublicProfileResponse.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/repository/UserRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/UserService.java
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-223?atlOrigin=eyJpIjoiNDU0ZTUwNzhkN2M2NDBlNmExNmQ0NjIxZDMwYTU0OWIiLCJwIjoiaiJ9
> [ feat / SCRUM-223 ] [ 프런트 요청 ] 타인 공개 프로필

- Sandwich/src/main/java/com/sandwich/SandWich/common/config/OpenApiConfig.java
- Sandwich/src/main/java/com/sandwich/SandWich/project/repository/ProjectRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/dto/AccountSearchItem.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/repository/UserRepository.java
- Sandwich/src/main/java/com/sandwich/SandWich/user/service/AccountSearchService.java
- Sandwich/src/main/resources/application.properties
Jira 백로그 >> https://hyeonjujo999.atlassian.net/browse/SCRUM-231?atlOrigin=eyJpIjoiM2FiYTVkODBhNzMwNDdjOTlkOWMzNDE3NGE2MjNkY2YiLCJwIjoiaiJ9
> [ feat / SCRUM-231 ] [ 프런트 요청 ] cover url 추가

- front/src/api/accounts.ts
- front/src/api/projects.ts
- front/src/components/AccountSearch/AccountCardGrid.tsx
- front/src/components/AccountSearch/AccountSearchContainer.tsx
- front/src/components/Auth/Login/LoginForm.tsx
- front/src/components/Auth/OAuth/OAuthSuccessHandler.tsx
- front/src/components/Profile/ProfilePage.tsx
- front/src/components/Profile/WorkTab.tsx
- front/src/components/ProjectFeed/ProjectFeedContainer.tsx
- front/src/components/ProjectFeed/ProjectPagination.tsx
- front/src/components/ProjectFeed/ProjectSearchBar.tsx
- front/src/components/common/Header/SearchBar.tsx
- front/src/context/AuthContext.tsx
- front/src/hooks/useAccountSearch.ts
- front/src/hooks/useProjectFeed.ts
- front/src/hooks/useRecentSearches.ts
- front/src/lib/fcm.ts
- front/src/pages/ProjectFeedPage.tsx
- front/src/utils/tokenStorage.ts
https://hyeonjujo999.atlassian.net/browse/SCRUM-235 참고
> Scrum 235 수정사항

- Sandwich/src/main/resources/application.properties
> RDS 이전 후 로컬 도커 삭제

- Sandwich/Dockerfile
firebase-service-account.json 임시 주석
> firebase-service-account.json 임시 주석
